### ISSUE TITLE
issue on Dataset

### ISSUE THREAD

**Issue by LeMei** [Max-Fu/tvl#1]
I am interested in your work. It is cool work.
When I did the command zip -s0 tvl_dataset_sharded.zip --out tvl_dataset.zip, I encontered  
zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (tvl_dataset_sharded.zip)

How to address it? Thanks in advance.

**Comment by Max-Fu** [comment]
Thanks for your interest in this work! I have not encountered this issue. I hypothesize that either 1) the file structure probably isn't right or 2) some of the zip files are corrupted. 
For 1): please verify if the folder contains all of tvl_dataset_sharded.z01, ..., tvl_dataset_sharded.z07 and tvl_dataset_sharded.zip. 
For 2): maybe try manually re-download the dataset from https://huggingface.co/datasets/mlfu7/Touch-Vision-Language-Dataset/tree/main

Please let me know if these fix your issue!

**Comment by LeMei** [comment]
I have addressed this issue. Now I encounter another issue about 'torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 273222)'.
I am not sure root cause of the issue. And I want to know what kind of device you train the model?

Thanks

**Comment by LeMei** [comment]
Do you use distributed training?

**Comment by Max-Fu** [comment]
We use distributed training. Does this problem occur with the tactile encoder or TVL-LLaMA? We use A100 for training the model.

**Comment by Max-Fu** [comment]
Please feel free to open this issue if you have any questions!
