### ISSUE TITLE
flash attention version

### ISSUE THREAD

**Issue by ofzlo** [Max-Fu/tvl#3]
Thanks for your awesome work!

Could you provide the version for the Flash Attention library?
I encounter conflicts when installing the Flash Attention library tailored for CUDA version 12.1.
Also, it'll be helpful to provide transformer version too!

**Comment by Max-Fu** [comment]
Thanks for your interest in our work! 

The dependencies we used are listed below: 
```
flash-attn               2.2.3.post2
transformers             4.37.0
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
```

Please feel free to let us know if you have any other questions!
